In [9]:
import pandas as pd

df = pd.read_excel("API_Download_DS2_en_excel_v2_58494.xls", sheet_name = "Work Data")

df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Armenia,ARM,"Internally displaced persons, new displacement...",VC.IDP.NWDS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Armenia,ARM,"Voice and Accountability: Percentile Rank, Upp...",VA.PER.RNK.UPPER,3.568075e+01,3.596059e+01,3.596059e+01,3.448276e+01,3.448276e+01,5.000000e+01,5.458937e+01,5.603865e+01,5.603865e+01,5.748792e+01,5.686274e+01
2,Armenia,ARM,Voice and Accountability: Estimate,VA.EST,-5.880992e-01,-5.621320e-01,-5.362738e-01,-5.790926e-01,-5.606704e-01,-1.309652e-01,5.478821e-02,4.734789e-02,5.416080e-02,9.032582e-02,7.670756e-02
3,Armenia,ARM,High-technology exports (current US$),TX.VAL.TECH.CD,9.332592e+06,9.307631e+06,1.186013e+07,2.184545e+07,2.828217e+07,3.652931e+07,4.557371e+07,2.651444e+07,3.756264e+07,4.971789e+08,8.225325e+08
4,Armenia,ARM,Merchandise exports to low- and middle-income ...,TX.VAL.MRCH.WR.ZS,1.013714e+01,9.644624e+00,1.057570e+01,1.048278e+01,8.467973e+00,5.058596e+00,5.101676e+00,4.758789e+00,5.060577e+00,6.691066e+00,4.720291e+00

In [10]:
df_melted = df.melt(
    id_vars=["Country Name", "Country Code", "Indicator Name", "Indicator Code"],
    var_name="Year",
    value_name="Value"
)

df_melted.head()

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value
0,Armenia,ARM,"Internally displaced persons, new displacement...",VC.IDP.NWDS,2013,NaN
1,Armenia,ARM,"Voice and Accountability: Percentile Rank, Upp...",VA.PER.RNK.UPPER,2013,3.568075e+01
2,Armenia,ARM,Voice and Accountability: Estimate,VA.EST,2013,-5.880992e-01
3,Armenia,ARM,High-technology exports (current US$),TX.VAL.TECH.CD,2013,9.332592e+06
4,Armenia,ARM,Merchandise exports to low- and middle-income ...,TX.VAL.MRCH.WR.ZS,2013,1.013714e+01

In [11]:
important_indicators = [
    "GDP per capita",
    "Inflation rate",
    "Exchange rate",
    "Human Rights Development Index",
    "Unemployment rate",
    "Literacy rate",
    "Economic Freedom",
    "Interest rate",
    "Access to electricity",
    "Technicians in R&D",
    "Age dependency ratio, old (% of working-age population)",
    "Regulatory Quality: Percentile Rank",
    "Control of Corruption: Percentile Rank, Lower Bound of 90% Confidence Interval",
    "Foreign direct investment, net outflows",
    "Land area (sq. km)",
    "Population, total"
]

mask = df_melted["Indicator Name"].apply(
    lambda x: any(keyword.lower() in x.lower() for keyword in important_indicators)
)
df_filtered = df_melted[mask]

In [12]:
df_pivoted = df_filtered.pivot_table(
    index=["Country Name", "Country Code", "Year"],
    columns="Indicator Name",
    values="Value"
).reset_index()

df_pivoted.columns.name = None

df_pivoted.head()

,Country Name,Country Code,Year,Access to electricity (% of population),"Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)","Age dependency ratio, old (% of working-age population)","Control of Corruption: Percentile Rank, Lower Bound of 90% Confidence Interval",Deposit interest rate (%),"Foreign direct investment, net outflows (% of GDP)",...,"Population, total",Price level ratio of PPP conversion factor (GDP) to market exchange rate,Real effective exchange rate index (2010 = 100),Real interest rate (%),Regulatory Quality: Percentile Rank,"Regulatory Quality: Percentile Rank, Lower Bound of 90% Confidence Interval","Regulatory Quality: Percentile Rank, Upper Bound of 90% Confidence Interval",Rural land area (sq. km),Technicians in R&D (per million people),Urban land area (sq. km)
0,Armenia,ARM,2013,99.4,99.4,99.4,15.376753,23.222750,10.160265,0.272112,...,3022000.0,0.389235,96.846684,12.216843,59.715641,52.132702,67.298576,NaN,NaN,NaN
1,Armenia,ARM,2014,99.7,99.8,99.7,15.542233,23.557692,10.425785,0.248108,...,3013800.0,0.395648,100.977872,13.781249,56.250000,48.076923,67.788460,NaN,NaN,NaN
2,Armenia,ARM,2015,100.0,100.0,100.0,15.840352,21.904762,14.148159,0.272444,...,3004600.0,0.359993,103.999506,16.180010,60.000000,48.095238,67.142860,27342.218295,NaN,922.335027
3,Armenia,ARM,2016,99.8,99.8,99.8,16.261821,16.666666,11.615657,0.668675,...,2992300.0,0.333428,102.619531,17.042360,62.380951,49.047619,68.571426,NaN,NaN,NaN
4,Armenia,ARM,2017,99.7,99.5,99.8,16.762553,19.047619,9.013335,0.252066,...,2979400.0,0.320657,99.313928,11.997340,62.857143,48.095238,71.428574,NaN,NaN,NaN

In [13]:
print(df_pivoted.columns.tolist())

['Country Name', 'Country Code', 'Year', 'Access to electricity (% of population)', 'Access to electricity, rural (% of rural population)', 'Access to electricity, urban (% of urban population)', 'Age dependency ratio, old (% of working-age population)', 'Control of Corruption: Percentile Rank, Lower Bound of 90% Confidence Interval', 'Deposit interest rate (%)', 'Foreign direct investment, net outflows (% of GDP)', 'Foreign direct investment, net outflows (BoP, current US$)', 'GDP per capita (constant 2015 US$)', 'GDP per capita (constant LCU)', 'GDP per capita (current LCU)', 'GDP per capita (current US$)', 'GDP per capita growth (annual %)', 'GDP per capita, PPP (constant 2021 international $)', 'GDP per capita, PPP (current international $)', 'Government expenditure per student, primary (% of GDP per capita)', 'Government expenditure per student, secondary (% of GDP per capita)', 'Government expenditure per student, tertiary (% of GDP per capita)', 'Interest rate spread (lending rate minus deposit rate, %)', 'Land area (sq. km)', 'Lending interest rate (%)', 'Literacy rate, adult female (% of females ages 15 and above)', 'Literacy rate, adult male (% of males ages 15 and above)', 'Literacy rate, adult total (% of people ages 15 and above)', 'Literacy rate, youth (ages 15-24), gender parity index (GPI)', 'Literacy rate, youth female (% of females ages 15-24)', 'Literacy rate, youth male (% of males ages 15-24)', 'Literacy rate, youth total (% of people ages 15-24)', 'Official exchange rate (LCU per US$, period average)', 'Population, total', 'Price level ratio of PPP conversion factor (GDP) to market exchange rate', 'Real effective exchange rate index (2010 = 100)', 'Real interest rate (%)', 'Regulatory Quality: Percentile Rank', 'Regulatory Quality: Percentile Rank, Lower Bound of 90% Confidence Interval', 'Regulatory Quality: Percentile Rank, Upper Bound of 90% Confidence Interval', 'Rural land area (sq. km)', 'Technicians in R&D (per million people)', 'Urban land area (sq. km)']

In [14]:
df_pivoted = df_pivoted.drop(columns=["Access to electricity, rural (% of rural population)","Access to electricity, urban (% of urban population)","Age dependency ratio, old (% of working-age population)", "Government expenditure per student, primary (% of GDP per capita)", "Government expenditure per student, secondary (% of GDP per capita)", "Government expenditure per student, secondary (% of GDP per capita)","Government expenditure per student, tertiary (% of GDP per capita)","Literacy rate, adult female (% of females ages 15 and above)", "Literacy rate, adult male (% of males ages 15 and above)","Literacy rate, youth female (% of females ages 15-24)", "Literacy rate, youth male (% of males ages 15-24)", "Literacy rate, youth total (% of people ages 15-24)","Price level ratio of PPP conversion factor (GDP) to market exchange rate","Rural land area (sq. km)"])
df_pivoted.head()

,Country Name,Country Code,Year,Access to electricity (% of population),"Control of Corruption: Percentile Rank, Lower Bound of 90% Confidence Interval",Deposit interest rate (%),"Foreign direct investment, net outflows (% of GDP)","Foreign direct investment, net outflows (BoP, current US$)",GDP per capita (constant 2015 US$),GDP per capita (constant LCU),...,"Literacy rate, youth (ages 15-24), gender parity index (GPI)","Official exchange rate (LCU per US$, period average)","Population, total",Real effective exchange rate index (2010 = 100),Real interest rate (%),Regulatory Quality: Percentile Rank,"Regulatory Quality: Percentile Rank, Lower Bound of 90% Confidence Interval","Regulatory Quality: Percentile Rank, Upper Bound of 90% Confidence Interval",Technicians in R&D (per million people),Urban land area (sq. km)
0,Armenia,ARM,2013,99.4,23.222750,10.160265,0.272112,3.026287e+07,3266.298830,1.458390e+06,...,NaN,409.625749,3022000.0,96.846684,12.216843,59.715641,52.132702,67.298576,NaN,NaN
1,Armenia,ARM,2014,99.7,23.557692,10.425785,0.248108,2.880408e+07,3393.092523,1.515003e+06,...,NaN,415.919789,3013800.0,100.977872,13.781249,56.250000,48.076923,67.788460,NaN,NaN
2,Armenia,ARM,2015,100.0,21.904762,14.148159,0.272444,2.875192e+07,3512.393503,1.568270e+06,...,NaN,477.918307,3004600.0,103.999506,16.180010,60.000000,48.095238,67.142860,NaN,922.335027
3,Armenia,ARM,2016,99.8,16.666666,11.615657,0.668675,7.051938e+07,3533.885036,1.577866e+06,...,1.0,480.488151,2992300.0,102.619531,17.042360,62.380951,49.047619,68.571426,NaN,NaN
4,Armenia,ARM,2017,99.7,19.047619,9.013335,0.252066,2.905682e+07,3815.374743,1.703550e+06,...,1.0,482.716394,2979400.0,99.313928,11.997340,62.857143,48.095238,71.428574,NaN,NaN

In [15]:
missing_percentage = df_pivoted.isna().mean() * 100
print(missing_percentage[missing_percentage > 0])

Interest rate spread (lending rate minus deposit rate, %)       20.000000
Land area (sq. km)                                               9.090909
Lending interest rate (%)                                       20.000000
Literacy rate, adult total (% of people ages 15 and above)      61.818182
Literacy rate, youth (ages 15-24), gender parity index (GPI)    60.000000
Real effective exchange rate index (2010 = 100)                 40.000000
Real interest rate (%)                                          20.000000
Technicians in R&D (per million people)                         69.090909
Urban land area (sq. km)                                        90.909091
dtype: float64

In [16]:
df_pivoted = df_pivoted.drop(columns=["Literacy rate, adult total (% of people ages 15 and above)", "Literacy rate, youth (ages 15-24), gender parity index (GPI)", "Real effective exchange rate index (2010 = 100)", "Technicians in R&D (per million people)", "Urban land area (sq. km)"])

In [17]:
columns_to_fill = ["Interest rate spread (lending rate minus deposit rate, %)", "Land area (sq. km)", "Lending interest rate (%)", "Real interest rate (%)"]
for col in columns_to_fill:
    df_pivoted[col] = df_pivoted[col].fillna(df_pivoted[col].mean())

In [18]:
df_pivoted.head()

,Country Name,Country Code,Year,Access to electricity (% of population),"Control of Corruption: Percentile Rank, Lower Bound of 90% Confidence Interval",Deposit interest rate (%),"Foreign direct investment, net outflows (% of GDP)","Foreign direct investment, net outflows (BoP, current US$)",GDP per capita (constant 2015 US$),GDP per capita (constant LCU),...,"GDP per capita, PPP (current international $)","Interest rate spread (lending rate minus deposit rate, %)",Land area (sq. km),Lending interest rate (%),"Official exchange rate (LCU per US$, period average)","Population, total",Real interest rate (%),Regulatory Quality: Percentile Rank,"Regulatory Quality: Percentile Rank, Lower Bound of 90% Confidence Interval","Regulatory Quality: Percentile Rank, Upper Bound of 90% Confidence Interval"
0,Armenia,ARM,2013,99.4,23.222750,10.160265,0.272112,3.026287e+07,3266.298830,1.458390e+06,...,9454.878528,5.834722,28470.0,15.994987,409.625749,3022000.0,12.216843,59.715641,52.132702,67.298576
1,Armenia,ARM,2014,99.7,23.557692,10.425785,0.248108,2.880408e+07,3393.092523,1.515003e+06,...,9736.234975,5.982880,28470.0,16.408665,415.919789,3013800.0,13.781249,56.250000,48.076923,67.788460
2,Armenia,ARM,2015,100.0,21.904762,14.148159,0.272444,2.875192e+07,3512.393503,1.568270e+06,...,9756.840848,3.442171,28470.0,17.590330,477.918307,3004600.0,16.180010,60.000000,48.095238,67.142860
3,Armenia,ARM,2016,99.8,16.666666,11.615657,0.668675,7.051938e+07,3533.885036,1.577866e+06,...,10570.272041,5.741049,28470.0,17.356706,480.488151,2992300.0,17.042360,62.380951,49.047619,68.571426
4,Armenia,ARM,2017,99.7,19.047619,9.013335,0.252066,2.905682e+07,3815.374743,1.703550e+06,...,12066.004309,5.392667,28470.0,14.406002,482.716394,2979400.0,11.997340,62.857143,48.095238,71.428574

In [19]:
df_pivoted.to_excel("cleaned_data_georgia_and_neighbours.xlsx", index=False)